import os

os.system("clear")
os.system("sudo dnf update -y")
os.system("sudo dnf autoremove -y")
os.system("sudo dnf install clamav clamtk -y")
os.system("sudo dnf install fail2ban -y")
os.system("sudo dnf install git -y")
os.system("sudo dnf install htop -y")
os.system("sudo dnf install neofetch -y")
os.system("sudo dnf install idle -y")
os.system("sudo dnf install chromium -y")
os.system("sudo dnf install gnome-shell-extension-caffeine.noarch -y")
os.system("sudo dnf install gnome-shell-extension-dash-to-dock.noarch -y")
os.system("sudo dnf install dnf-plugins-core")
os.system("sudo dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/")
os.system("sudo rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc")
os.system("sudo dnf install brave-browser -y")
os.system("cd Downloads")
os.system("git clone https://github.com/Invizabel/Pixel")
os.system("unzip Pixel-main.zip")
os.system("cd Pixel-main")
os.system("unzip Pixel")
os.system("sudo cp -r Pixel /usr/share/icons")
os.system("cd -")
os.system("sudo rm Pixel-main.zip")
os.system("sudo rm -r Pixel-main")
os.system('gsettings set org.gnome.desktop.interface icon-theme "Pixel"')
